name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main  # 사용할 브랜치

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@1.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}